DROP TABLE IF EXISTS images;

CREATE TABLE images(
    id SERIAL PRIMARY KEY,
    image VARCHAR(300) NOT NULL,
    username VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




DROP TABLE IF EXISTS comments;

CREATE TABLE comments(
    commentid SERIAL PRIMARY KEY,
    comment VARCHAR(300) NOT NULL,
    userid VARCHAR(255) NOT NULL,
    iamgeid VARCHAR (2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
